"""Add latitude and longitude to PetLostReport

Revision ID: 1c01d1c6d874
Revises: f1d8dcfecd1a
Create Date: 2025-05-03 13:55:55.734310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c01d1c6d874'
down_revision = 'f1d8dcfecd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('contact_info',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_index('ix_pet_lost_reports_is_found')
        batch_op.drop_column('lost_longitude')
        batch_op.drop_column('lost_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lost_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lost_longitude', sa.FLOAT(), nullable=True))
        batch_op.create_index('ix_pet_lost_reports_is_found', ['is_found'], unique=False)
        batch_op.alter_column('contact_info',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
