"""Add pet_name and additional_info to PetLostReport

Revision ID: 37da5a236528
Revises: 1d2bfef76e03
Create Date: 2025-06-10 15:57:27.520045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da5a236528'
down_revision = '1d2bfef76e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('pet_name')

    # ### end Alembic commands ###
