"""Initial migration with pet report tables

Revision ID: ac1c1522f922
Revises: 
Create Date: 2025-05-02 13:11:21.280301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1c1522f922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_found_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_openid', sa.String(length=128), nullable=True),
    sa.Column('pet_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('found_time', sa.DateTime(), nullable=False),
    sa.Column('found_location_text', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=False),
    sa.Column('_photo_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_found_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_found_reports_user_openid'), ['user_openid'], unique=False)

    op.create_table('pet_lost_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_openid', sa.String(length=128), nullable=True),
    sa.Column('pet_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('lost_time', sa.DateTime(), nullable=False),
    sa.Column('lost_location_text', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=False),
    sa.Column('_photo_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_lost_reports_user_openid'), ['user_openid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_lost_reports_user_openid'))

    op.drop_table('pet_lost_reports')
    with op.batch_alter_table('pet_found_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_found_reports_user_openid'))

    op.drop_table('pet_found_reports')
    # ### end Alembic commands ###
