"""Add is_found and found_time to PetLostReport

Revision ID: d48b8cef9cc7
Revises: ac1c1522f922
Create Date: 2025-05-03 11:31:13.249425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48b8cef9cc7'
down_revision = 'ac1c1522f922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        # Adjust for SQLite: Add server_default for NOT NULL column
        batch_op.add_column(sa.Column('is_found', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('found_time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pet_lost_reports_is_found'), ['is_found'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_lost_reports_is_found'))
        batch_op.drop_column('found_time')
        batch_op.drop_column('is_found')

    # ### end Alembic commands ###
