"""Add latitude and longitude to PetLostReport

Revision ID: f1d8dcfecd1a
Revises: d48b8cef9cc7
Create Date: 2025-05-03 12:20:42.163923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d8dcfecd1a'
down_revision = 'd48b8cef9cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lost_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lost_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_lost_reports', schema=None) as batch_op:
        batch_op.drop_column('lost_longitude')
        batch_op.drop_column('lost_latitude')

    # ### end Alembic commands ###
